<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPyYGRqb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPyYGRqb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPyYGRqb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPyYGRqb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPyYGRqb\App_KernelDevDebugContainer([
    'container.build_hash' => 'PyYGRqb',
    'container.build_id' => '97dce60b',
    'container.build_time' => 1652931958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPyYGRqb');
